id: A684B79DA
title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
type: translation
pechas:
- I8683D586
- IB0B15E0C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:59.963137
  last_modified_at: 2023-01-04 13:08:59.963143
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8683D586/B746: 2B0D
  IB0B15E0C/3407: 2B0D
